name: Build and deploy Node.js app with TypeScript to Azure Web App - flashlight

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Build TypeScript
        run: pnpm run build

      - name: Zip artifact for deployment
        run: zip release.zip -r .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'flashlight'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F7344A5AC68446CDA928161085C9B7B6 }}
          package: .

      - name: Install production dependencies
        run: pnpm ci --production
        working-directory: backend

      - name: Start Express server
        run: pnpm start
        working-directory: backend
